-- 0206_データベース項目定義書.xlsx から作成した Supabase / PostgreSQL 用DDL
-- 想定: Supabase SQL Editor / PostgreSQL
-- 方針:
--   - MySQL構文をPostgreSQL構文へ変換
--   - Supabaseで扱いやすいようにテーブル名・カラム名を小文字 snake_case に統一
--   - ユーザーIDは Supabase Auth の auth.users.id と同じ uuid として扱う
--   - AUTO_INCREMENT は GENERATED BY DEFAULT AS IDENTITY に変換
--   - MySQLの COMMENT は COMMENT ON に変換
--   - updated_at は更新時に自動更新するトリガーを付与

begin;

create extension if not exists "pgcrypto";

-- 既存テーブルを削除する場合は依存関係があるため子テーブルから削除
-- 初回作成だけなら、このDROP文は削除して実行しても問題ありません。
drop table if exists public.shopping cascade;
drop table if exists public.favorites cascade;
drop table if exists public.cooking_history cascade;
drop table if exists public.inventory cascade;
drop table if exists public.recipe_ingredients cascade;
drop table if exists public.recipes cascade;
drop table if exists public.ingredient_management cascade;
drop table if exists public.user_allergies cascade;
drop table if exists public.allergies cascade;
drop table if exists public.users cascade;
drop function if exists public.set_updated_at() cascade;

create table public.users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  user_name varchar(50),
  user_mail varchar(255) not null unique,
  user_age integer,
  gender varchar(10),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.users is '顧客テーブル';
comment on column public.users.user_id is 'ユーザーID。Supabase Authのauth.users.idを参照';
comment on column public.users.user_name is 'ユーザー名';
comment on column public.users.user_mail is 'メールアドレス';
comment on column public.users.user_age is '年齢';
comment on column public.users.gender is '性別';
comment on column public.users.created_at is '作成日';
comment on column public.users.updated_at is '更新日';

create table public.allergies (
  allergy_id bigint generated by default as identity primary key,
  allergy_name varchar(50)
);

comment on table public.allergies is 'アレルギー一覧テーブル';
comment on column public.allergies.allergy_id is 'アレルギーID';
comment on column public.allergies.allergy_name is 'アレルゲン';

create table public.user_allergies (
  user_id uuid not null references public.users(user_id) on delete cascade,
  allergy_id bigint not null references public.allergies(allergy_id) on delete restrict,
  created_at timestamptz not null default now(),
  primary key (user_id, allergy_id)
);

comment on table public.user_allergies is 'ユーザーアレルギーテーブル';
comment on column public.user_allergies.user_id is 'ユーザーID / 外部キー';
comment on column public.user_allergies.allergy_id is 'アレルギーID / 外部キー';
comment on column public.user_allergies.created_at is '作成日';

create table public.ingredient_management (
  ingredient_id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(user_id) on delete cascade,
  ingredient_name varchar(100),
  category varchar(30),
  barcode varchar(50),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.ingredient_management is '食材マスターテーブル';
comment on column public.ingredient_management.ingredient_id is '食材ID';
comment on column public.ingredient_management.user_id is 'ユーザーID / 外部キー';
comment on column public.ingredient_management.ingredient_name is '食材名';
comment on column public.ingredient_management.category is 'カテゴリー';
comment on column public.ingredient_management.barcode is 'バーコード';
comment on column public.ingredient_management.created_at is '登録日';
comment on column public.ingredient_management.updated_at is '更新日';

create table public.recipes (
  recipe_id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(user_id) on delete cascade,
  name varchar(100),
  cook_time integer,
  cook_process text,
  url varchar(255),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.recipes is 'レシピテーブル';
comment on column public.recipes.recipe_id is 'レシピID / UUIDで生成';
comment on column public.recipes.user_id is 'ユーザーID / 外部キー';
comment on column public.recipes.name is 'レシピ名';
comment on column public.recipes.cook_time is '調理時間';
comment on column public.recipes.cook_process is '工程';
comment on column public.recipes.url is 'リンク';
comment on column public.recipes.created_at is '作成日';
comment on column public.recipes.updated_at is '更新日';

create table public.recipe_ingredients (
  recipe_ingredient_id bigint generated by default as identity primary key,
  recipe_id uuid not null references public.recipes(recipe_id) on delete cascade,
  ingredient_id bigint not null references public.ingredient_management(ingredient_id) on delete restrict,
  required_amount numeric(5, 2),
  unit varchar(20)
);

comment on table public.recipe_ingredients is 'レシピ食材テーブル';
comment on column public.recipe_ingredients.recipe_ingredient_id is '識別ID';
comment on column public.recipe_ingredients.recipe_id is 'レシピID / 外部キー';
comment on column public.recipe_ingredients.ingredient_id is '食材ID / 外部キー';
comment on column public.recipe_ingredients.required_amount is '必要量';
comment on column public.recipe_ingredients.unit is '単位';

create table public.inventory (
  inventory_id bigint generated by default as identity primary key,
  ingredient_id bigint not null references public.ingredient_management(ingredient_id) on delete cascade,
  user_id uuid not null references public.users(user_id) on delete cascade,
  quantity integer,
  gram integer,
  expiration_date date,
  purchase_date date,
  memo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.inventory is '食材管理テーブル';
comment on column public.inventory.inventory_id is '管理ID';
comment on column public.inventory.ingredient_id is '食材ID / 外部キー';
comment on column public.inventory.user_id is 'ユーザーID / 外部キー';
comment on column public.inventory.quantity is '個数';
comment on column public.inventory.gram is '重量';
comment on column public.inventory.expiration_date is '期限';
comment on column public.inventory.purchase_date is '購入日';
comment on column public.inventory.memo is 'メモ';
comment on column public.inventory.created_at is '作成日';
comment on column public.inventory.updated_at is '更新日';

create table public.cooking_history (
  history_id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(user_id) on delete cascade,
  recipe_id uuid not null references public.recipes(recipe_id) on delete cascade,
  cooked_at timestamptz not null default now()
);

comment on table public.cooking_history is '調理履歴';
comment on column public.cooking_history.history_id is '履歴ID';
comment on column public.cooking_history.user_id is 'ユーザーID / 外部キー';
comment on column public.cooking_history.recipe_id is 'レシピID / 外部キー';
comment on column public.cooking_history.cooked_at is '調理日';

create table public.favorites (
  user_id uuid not null references public.users(user_id) on delete cascade,
  recipe_id uuid not null references public.recipes(recipe_id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, recipe_id)
);

comment on table public.favorites is 'お気に入り';
comment on column public.favorites.user_id is 'ユーザーID / 外部キー';
comment on column public.favorites.recipe_id is 'レシピID / 外部キー';
comment on column public.favorites.created_at is '作成日';

create table public.shopping (
  shopping_id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(user_id) on delete cascade,
  ingredient_id bigint references public.ingredient_management(ingredient_id) on delete set null,
  necessary_amount numeric(6, 2),
  unit varchar(20),
  memo text,
  delete_flag boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.shopping is '食材買い物テーブル';
comment on column public.shopping.shopping_id is '買うものID';
comment on column public.shopping.user_id is 'ユーザーID / 外部キー';
comment on column public.shopping.ingredient_id is '食材ID / 外部キー';
comment on column public.shopping.necessary_amount is '必要個数';
comment on column public.shopping.unit is '単位。元定義ではINTでしたが、g/個/mlなどを扱いやすいようvarchar(20)に変換';
comment on column public.shopping.memo is 'メモ';
comment on column public.shopping.delete_flag is '削除フラグ';
comment on column public.shopping.created_at is '追加日';
comment on column public.shopping.updated_at is '更新日';

-- updated_at 自動更新用トリガー
create function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger set_users_updated_at
before update on public.users
for each row execute function public.set_updated_at();

create trigger set_ingredient_management_updated_at
before update on public.ingredient_management
for each row execute function public.set_updated_at();

create trigger set_recipes_updated_at
before update on public.recipes
for each row execute function public.set_updated_at();

create trigger set_inventory_updated_at
before update on public.inventory
for each row execute function public.set_updated_at();

create trigger set_shopping_updated_at
before update on public.shopping
for each row execute function public.set_updated_at();

-- Supabase向け Row Level Security
-- フロントエンドからanon/authenticated keyで操作する場合に、ログイン中ユーザーの行だけ操作できるようにします。
alter table public.users enable row level security;
alter table public.allergies enable row level security;
alter table public.user_allergies enable row level security;
alter table public.ingredient_management enable row level security;
alter table public.recipes enable row level security;
alter table public.recipe_ingredients enable row level security;
alter table public.inventory enable row level security;
alter table public.cooking_history enable row level security;
alter table public.favorites enable row level security;
alter table public.shopping enable row level security;

create policy "users_select_own" on public.users
  for select to authenticated
  using (auth.uid() = user_id);

create policy "users_insert_own" on public.users
  for insert to authenticated
  with check (auth.uid() = user_id);

create policy "users_update_own" on public.users
  for update to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "allergies_select_authenticated" on public.allergies
  for select to authenticated
  using (true);

create policy "user_allergies_own_rows" on public.user_allergies
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "ingredient_management_own_rows" on public.ingredient_management
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "recipes_own_rows" on public.recipes
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "recipe_ingredients_own_rows" on public.recipe_ingredients
  for all to authenticated
  using (
    exists (
      select 1
      from public.recipes r
      where r.recipe_id = recipe_ingredients.recipe_id
        and r.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.recipes r
      where r.recipe_id = recipe_ingredients.recipe_id
        and r.user_id = auth.uid()
    )
  );

create policy "inventory_own_rows" on public.inventory
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "cooking_history_own_rows" on public.cooking_history
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "favorites_own_rows" on public.favorites
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "shopping_own_rows" on public.shopping
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

commit;
